title: Logan Van Vuren
logo: "/images/snipphoto.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hello! I am a recent graduate from Seattle Pacific University where I majored in Information Systems (June 2021), and I have always been interested in how data can help us understand our world around us. 
  <br><br>
  My career interests are in Data Analytics and Cloud Infrastructure, and I enjoy rock climbing, playing piano, and cooking.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
